Solving a 1st order ODE Boundary Value problems

$$\frac{dy}{dx} = x^{2}$$

forward difference, backward difference, average difference
$$
y_{i+1} - y_i / del = f
$$$$
y_{i+1} - y_i = f*del
$$$$
y_1 - y_0 = delf0
$$$$
y_2 - y_1 = delf1
$$
.
.
.
into matrix form: Ay = f  -> y = A^-1f
$$

In [2]:
import matplotlib.pyplot as plt
import time
import math
import vector as vec
import matrix as mat

def first_order_1d(a, b, N, rhs, bc):
    delta = (b - a)/(N-1)
    A = matrix.matrix(N, N)
    b = vector.vector(N)
    x = vector.vector(N)
    
    for i in range(N):
        A[i, i, ] = -1
        try:
            A[i, i+1] = 1
        except Exception as e:
            pass
        b[i] = delta*rhs(i*delta)
        x[i] = a+delta*i
    indices = list(bc.keys())
    # first order has 1 BC
    index = indices[0]
    bc_val= bc[index]
    
    A[index, index] = b[index]/bc_val   
    try:
        A[index, index+1] = 0
    except Exception as e:
        pass
    begin_time = time.time()
    A_inv = matrix.inverse(A)
    y = A_inv.inner(b)
    end_time = time.time()
    compute_time = (end_time-begin_time)*1000
    
    return x, y, compute_time

# Basic setup
N_list = []
t_list = []

# right hand side (rhs) of dif eq
rhs = lambda x: x*x
a = 0
b = 2

# tabulated form
x = [a + (b-a) / 99*i for i in range(100)]
y = [(xx**3 - 2)/3 for xx in x]

N = 3
bc = {2:2}
x_3, y_3, t_3 = first_order_1d(a, b, N, rhs, bc)
plt.plot(x_3.v, y_3.v, label = 'N=3')
N_list.append(N)
t_list.append(t_3)
print(f"N={N} is done!")

N = 5
bc = {4:2}
x_5, y_5, t_5 = first_order_1d(a, b, N, rhs, bc)
plt.plot(x_5.v, y_5.v, label = 'N=5')
N_list.append(N)
t_list.append(t_5)
print(f"N={N} is done!")

N = 7
bc = {6:2}
x_7, y_7, t_7 = first_order_1d(a, b, N, rhs, bc)
plt.plot(x_7.v, y_7.v, label = 'N=7')
N_list.append(N)
t_list.append(t_7)
print(f"N={N} is done!")

N = 10
bc = {9:2}
x_10, y_10, t_10 = first_order_1d(a, b, N, rhs, bc)
plt.plot(x_10.v, y_10.v, label = 'N=10')
N_list.append(N)
t_list.append(t_10)
print(f"N={N} is done!")

plt.xlabel('x')
plt.ylabel('y')
plt.plot(x, y, label = 'y(x)')
plt.legend()
plt.xlabel('N')
plt.ylabel('Time (ms)')
plt.yscale('log')
plt.plot(N_list, t_list)
plt.show()
    



    
    

ModuleNotFoundError: No module named 'vector'

$$ \frac{dy}{dx} = f$$
$$Ay = b$$
$$ y = bA^{-1}$$

\text{cannot use many N as it is too long, we use gaussian and backsubstitution}

In [3]:
import numpy as np
import time
import matplotlib.pyplot as plt

def exchange_rows(a, i, j):
    for k in range(len(a)):
        tmp = a[i][k]
        a[i][k] = a[j][k]
        a[j][k] = tmp
    return a


def gaussian_upper_triangle(a, b):
    C = np.column_stack((a, b))
    
    for i in range(len(C)):
        if C[i][i] == 0:
            if i < len(C) - 1:
                exchange_rows(C, i, i+1)
        else:
            diag = C[i][i]
            for k in range(i+1, len(C)):
                C[k] = C[k]*diag - C[i]*C[k][i]
    return C


def back_substitution(A):
    N = len(A)
    x = np.zeros(N)
    
    x[N-1] = A[N-1][N]/A[N-1][N-1]
    
    for i in range(N-2, -1, -1):
        s = 0
        for j in range(i+1, N):
            s += A[i][j]*x[j]
        s = A[i][N] - s
        s /= A[i][i]
        x[i] = s
    return x


if __name__ == '__main__':
    A = np.array([[2.0, 1.0, -1.0], [-3.0, -1.0, 2.0], [-2.0, 1.0, 2.0]])
    b = np.array([8, -11, -3])
    
    c = gaussian_upper_triangle(A, b)
    x = back_substitution(c)
    
    test = np.linalg.solve(A, b)
    print(c, x, test)
    print(A.dot(x), b)


[[ 2.  1. -1.  8.]
 [ 0.  1.  1.  2.]
 [ 0.  0. -2.  2.]] [ 2.  3. -1.] [ 2.  3. -1.]
[  8. -11.  -3.] [  8 -11  -3]


\text{}